<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>9.0.0</Version>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <EnableHarmony>true</EnableHarmony>
    <Nullable>enable</Nullable>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
    <DebugType>portable</DebugType>

    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>

    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <NoWarn>$(NoWarn);CA2252</NoWarn>

    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <BundleExtraAssemblies>ThirdParty</BundleExtraAssemblies>

    <EnableModZip>false</EnableModZip>
    <!-- <EnableModDeploy>false</EnableModDeploy> -->
    <GamePath>../stardew_install_symlink</GamePath>
    <EnableModDeploy>true</EnableModDeploy>
    <GameModsPath>../Mods</GameModsPath>

    <!-- <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath> -->
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="releases\**" />
    <EmbeddedResource Remove="releases\**" />
    <None Remove="releases\**" />
  </ItemGroup>

  <PropertyGroup>
    <WarningsAsErrors>CS8509</WarningsAsErrors>
    <WarningsAsErrors>CS8618</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dunet" Version="1.16.2" IncludeAssets="analyzers; build" />

    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.1.1" />
    <PackageReference Include="PolySharp" Version="1.16.0" />
    <PackageReference Include="System.Collections.Immutable" Version="10.0.11" />
    <PackageReference Include="System.Runtime.Experimental" Version="6.0.2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.*" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="SkiaSharp">
      <HintPath>$(GamePath)\SkiaSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConsoleLog\ConsoleLog.csproj" />
    <ProjectReference Include="..\DralGeometry\DralGeometry.csproj" />
    <ProjectReference Include="..\Prisms\Prisms.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <None Update="i18n\**.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <!-- <None Update="manifest.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None> -->
  </ItemGroup>

  <Target Name="RepackMod" AfterTargets="Build">
    <ItemGroup>
      <InputAssemblies Include="$(TargetPath)" />
      <InputAssemblies Include="$(TargetDir)System.Collections.Immutable.dll" />
    </ItemGroup>

    <ILRepack
      Parallel="true"
      Internalize="true"
      RenameInternalized="true"
      InputAssemblies="@(InputAssemblies)"
      OutputFile="$(TargetPath)"
      LibraryPath="$(TargetDir);@(ReferencePath->'%(RootDir)%(Directory)'->Distinct())"
    />
  </Target>

  <PropertyGroup>
    <PostBuildEventDependsOn>
			$(PostBuildEventDependsOn);
			PostBuildMacros;
		</PostBuildEventDependsOn>
  </PropertyGroup>
</Project>
